version: '3'

services:
  nextcap:
    image: node:18.17.0-alpine
    hostname: nextcap
    container_name: nextcap
    environment:
    - VIRTUAL_HOST=nextcap.${LETSENCRYPT_HOST}
    - LETSENCRYPT_HOST=nextcap.${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    volumes:
      - .:/app
      - ./.next.dev:/.next
    working_dir: /app
    # command: tail -f /dev/null
    # command: "npm run dev"
    command: "npm run start"
    networks:
      main-net: 

  capacitor:
    image: node:18.17.0-alpine
    hostname: capacitor
    container_name: capacitor
    environment:
    - VIRTUAL_HOST=capacitor.${LETSENCRYPT_HOST}
    - LETSENCRYPT_HOST=capacitor.${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    volumes:
      - .:/app
      - ./.next.prod:/.next
    working_dir: /app
    command: tail -f /dev/null
    # command: "npm run dev"
    # command: "npm run start"
    networks:
      main-net: 

networks:
  main-net:
    external:
      name: proxy_main-net