version: '3'

services:
  nextcap:
    image: node:18.17.0-alpine
    hostname: nextcap
    container_name: nextcap
    environment:
    - VIRTUAL_HOST=nextcap.${LETSENCRYPT_HOST}
    - LETSENCRYPT_HOST=nextcap.${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    volumes:
      - .:/app
      - ./.next.dev:/app/.next
    working_dir: /app
    # command: tail -f /dev/null
    command: "npm run dev"
    # command: "npm run start"
    networks:
      main-net: 

  capacitor:
    image: node:18.17.0-alpine
    hostname: capacitor
    container_name: capacitor
    environment:
    - VIRTUAL_HOST=capacitor.${LETSENCRYPT_HOST}
    - LETSENCRYPT_HOST=capacitor.${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    volumes:
      - .:/app
      - ./.next.prod:/app/.next
      # configure for server or static (use matching command)
      - ./next.config.server.mjs:/app/next.config.mjs
      # - ./next.config.static.mjs:/app/next.config.mjs
    working_dir: /app
    # run interactve, dev, server or static
    # command: tail -f /dev/null
    # command: "npm run dev"
    command: "npm run start"
    # command: "npx serve@latest out" 
    networks:
      main-net: 

networks:
  main-net:
    external:
      name: proxy_main-net