// 'use client'

import type { Metadata, Viewport } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
    viewportFit: 'cover',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>
        {children}
    </>
}